# Generated by Django 4.2.5 on 2023-11-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_budget_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='budget',
        ),
        migrations.AddField(
            model_name='event',
            name='firebase_user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
